### ISSUE TITLE
Support for Blurhash

### ISSUE THREAD

**Issue by imsheldon** [benmneb/mui-image#1]
Does this package supports blurhash? I want to use blurhash as loading indicator, how do I achieve that?

**Comment by benmneb** [comment]
I've never used Blurhash so I don't know about it, sorry.

What i do know is that the `showLoading` prop accepts any JSX element, and the image doesn't fade in from the loading indicator, it fades in from the color chosen in the `bgColor` prop. So if you're trying to make the Blurhash fade into the photo once it's loaded (similar to what Medium.com does) it won't work. There are other packages that do this, though without the Material guidelines level adjustments. An additional `placeholder` prop could be added for use cases like this, though I'm not certain how good it will look due to the progressive level adjustments the image goes through as it appears.
