### ISSUE TITLE
Using mui v5 styled function on this component don't overwrite preset inline style

### ISSUE THREAD

**Issue by mddanish00** [benmneb/mui-image#8]
I tried to use styled on this component but...
# Test code
```
import React from "react";
import Box from "@mui/system/Box";
import Image from "mui-image";

const CardImage = styled(Image)`
  margin: 0 auto;
  max-width: 100%;
  display: block;
  height: auto;
  width: auto;
  max-height: 500px;
`;

const FeaturedMedia = () => {
return (
    <Box mb={2}>
      <CardImage
        alt={"some title"}
        src={"https://picsum.photos/id/674/2000"}
      />
    </Box>
}
```
Look through Chrome DevTools, it strikeout on height: auto and width: auto... 
It prioritises your preset inline style more.

I copied your Image.js code and tried fixing it myself... 
Look like, the best way is just to move all preset styles to styled.

**Comment by benmneb** [comment]
I'm not sure exactly what you're trying to achieve, but...

Have you tried using the `height` and `width` props on the Image component? They target the wrapper div the image sits in, which should have the desired effect, because the `img` element by default is 100% of this wrapper.

Alternatively the `wrapperStyle` prop (which accepts a style object) will do the same thing.

If you need to target the actual `img` element the `style` prop will override the defaults.

Also, depending on the context, adjusting the `fit` prop might do the trick.

[Here's a codesandbox showing a few different options](https://codesandbox.io/s/pensive-morning-1g7t3p?file=%2Fsrc%2FApp.js).
